from django.contrib import admin
from .models import *
# Register your models here.

admin.site.register(UserBrowsingBehavior)
admin.site.register(UserBankAccount)
admin.site.register(User)
admin.site.register(Subcategory)
admin.site.register(ShopInfo)
admin.site.register(Shop)
admin.site.register(SellerProfile)
admin.site.register(Role)
admin.site.register(ProductVideo)
admin.site.register(ProductRecommendation)
admin.site.register(ProductImage)
admin.site.register(ProductAd)
admin.site.register(Product)
admin.site.register(Payment)
admin.site.register(OrderItem)
admin.site.register(Order)
admin.site.register(Notification)
admin.site.register(Comment)
admin.site.register(Category)
admin.site.register(CartItem)
admin.site.register(Cart)
# admin.site.register(AdView)
admin.site.register(Ad)